### ISSUE TITLE
TODO: Support settings of last application launch 

### ISSUE THREAD

**Issue by IlyaSuponev** [spbu-coding-2023/graphs-graphs-12#35]
Требуется проработать сохранение настроек при закрытии программы:
* `Theme` - цвета, типография, и др.
* `History` - история открытия в программе графов
* возможно что-то ещё.

Также требуется обработать закгрузку настроек прошлого запуска, при этом если "старая" конфигурация не найдена, то загрузить настройки поумолчанию, посути ничего не делать.

Для работы над этой задачей требуется работать в ветке: `config`.

**Comment by RodionovMaxim05** [comment]
Опять работа? Я беру

**Comment by IlyaSuponev** [comment]
Вследствии обновления, задача объявляется закрытой.
